inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - bloomberg_currency.gemspec
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

Metrics/AbcSize:
  Max: 18
